# This file was generated by `qmk generate-rules-mk`. Do not edit or copy.

BOOTLOADER ?= atmel-dfu
LAYOUTS ?= ['66_ansi', '66_iso']
MCU ?= atmega32u4
AUDIO_ENABLE ?= no
BACKLIGHT_ENABLE ?= yes
BLUETOOTH_ENABLE ?= no
BOOTMAGIC_ENABLE ?= no
COMMAND_ENABLE ?= no
CONSOLE_ENABLE ?= yes
EXTRAKEY_ENABLE ?= yes
MIDI_ENABLE ?= no
MOUSEKEY_ENABLE ?= yes
NKRO_ENABLE ?= yes
RGBLIGHT_ENABLE ?= yes
UNICODE_ENABLE ?= no
